### ISSUE TITLE
Not a beta release

### ISSUE THREAD

**Issue by Zt-freak** [ZT2Indonesia/Bear-Baby-ZT2-New-Animal-Mod-Promo-Official#2]
The image on your readme suggests this animal is from a beta release of the game, this however is questionable, because beta releases of Zoo Tycoon 2 are considered to be lost media.

**Comment by ZT2Indonesia** [comment]
Apologize Zt Freak be careful stay it's already download

**Comment by Zt-freak** [comment]
Do you have a Zoo Tycoon 2 Beta release in your possession?

**Comment by ZT2Indonesia** [comment]
Um. yes but i'm sadly **beta Build Zoo Tycoon 2 2004** Early Pre release did you see for looking source video have disc could need bring download begin help? 😥 here youtube link : https://www.youtube.com/watch?v=6s-VnhNq9F4 or https://www.youtube.com/watch?v=jB8Xl3qM4yA

**Comment by Zt-freak** [comment]
I'm sorry, I think there is a communication barrier here that is difficult to go across.

**Comment by ZT2Indonesia** [comment]
ok

**Comment by Zt-freak** [comment]
horse14t membeli disk Zoo Tycoon 2 Beta, tetapi hilang saat pengiriman. Jadi dia tidak pernah mendapatkan Beta, sayangnya.

**Comment by ZT2Indonesia** [comment]
ya tahu Sebenarnya yang ingin belum pengtahui inofrmasi ZT2 Beta 2 hanya dua Masih ada tentang?

**Comment by ZT2Indonesia** [comment]
Mungkin sedang mencari tak ketemu download Sama lain tanya aja atau gak punya Disc....

**Comment by Zt-freak** [comment]
Saya ragu ZT2 Beta tersedia untuk diunduh.
Peluang terbaik yang kami miliki adalah disk, tetapi satu-satunya yang kami tahu hilang saat pengiriman.

**Comment by ZT2Indonesia** [comment]
Merngerti setuju
